-- V1.0.3__baseline_migration.sql
-- 从 v1.0.2 升级到 v1.0.3+ 的数据库迁移脚本

-- 0. 创建基础表（如果不存在）- 支持全新数据库初始化
CREATE TABLE IF NOT EXISTS platform (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    `system` VARCHAR(100) NOT NULL,
    software VARCHAR(100) NOT NULL,
    `database` VARCHAR(100) NOT NULL,
    web VARCHAR(200) NOT NULL,
    name VARCHAR(255) NOT NULL,
    sort_by VARCHAR(50),
    launch TEXT,
    folder_path VARCHAR(1024),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS game (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    game_id VARCHAR(100) NOT NULL,
    source VARCHAR(100),
    `path` VARCHAR(1024) NOT NULL,
    `name` VARCHAR(255) NOT NULL,
    `desc` TEXT,
    translated_name VARCHAR(255),
    translated_desc TEXT,
    image VARCHAR(255),
    video VARCHAR(255),
    marquee VARCHAR(255),
    thumbnail VARCHAR(255),
    manual VARCHAR(255),
    rating DOUBLE,
    releasedate VARCHAR(50),
    developer VARCHAR(100),
    publisher VARCHAR(100),
    genre VARCHAR(100),
    players VARCHAR(20),
    crc32 VARCHAR(20),
    md5 VARCHAR(32),
    lang VARCHAR(20),
    genreid VARCHAR(20),
    sort_by VARCHAR(50),
    platform_id BIGINT,
    scraped BOOLEAN DEFAULT false,
    edited BOOLEAN DEFAULT false,
    `exists` BOOLEAN DEFAULT false,
    absolute_path VARCHAR(2048),
    platform_path VARCHAR(2048),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (platform_id) REFERENCES platform(id),
    box_front VARCHAR(255),
    box_back VARCHAR(255),
    box_spine VARCHAR(255),
    box_full VARCHAR(255),
    cartridge VARCHAR(255),
    logo VARCHAR(255),
    bezel VARCHAR(255),
    panel VARCHAR(255),
    cabinet_left VARCHAR(255),
    cabinet_right VARCHAR(255),
    tile VARCHAR(255),
    banner VARCHAR(255),
    steam VARCHAR(255),
    poster VARCHAR(255),
    background VARCHAR(255),
    music VARCHAR(255),
    screenshot VARCHAR(255),
    titlescreen VARCHAR(255),
    box3d VARCHAR(255),
    steamgrid VARCHAR(255),
    fanart VARCHAR(255),
    boxtexture VARCHAR(255),
    supporttexture VARCHAR(255),
    videonormalized VARCHAR(255),
    wheelcarbon VARCHAR(255),
    wheelsteel VARCHAR(255),
    screenmarqueesmall VARCHAR(255),
    boxside VARCHAR(255),
    figurine VARCHAR(255)
);

-- 创建临时子集表
CREATE TABLE IF NOT EXISTS temp_subset (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    creator_id BIGINT DEFAULT 1,
    status VARCHAR(50) DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 创建临时子集游戏表
CREATE TABLE IF NOT EXISTS temp_subset_game (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    subset_id BIGINT NOT NULL,
    original_game_id BIGINT NOT NULL,
    game_id VARCHAR(100) NOT NULL,
    source VARCHAR(100),
    `path` VARCHAR(1024) NOT NULL,
    `name` VARCHAR(255) NOT NULL,
    `desc` TEXT,
    translated_name VARCHAR(255),
    translated_desc TEXT,
    image VARCHAR(255),
    video VARCHAR(255),
    marquee VARCHAR(255),
    thumbnail VARCHAR(255),
    manual VARCHAR(255),
    rating DOUBLE,
    releasedate VARCHAR(50),
    developer VARCHAR(100),
    publisher VARCHAR(100),
    genre VARCHAR(100),
    players VARCHAR(20),
    crc32 VARCHAR(20),
    md5 VARCHAR(32),
    lang VARCHAR(20),
    genreid VARCHAR(20),
    sort_by VARCHAR(50),
    platform_id BIGINT,
    scraped BOOLEAN DEFAULT false,
    edited BOOLEAN DEFAULT false,
    `exists` BOOLEAN DEFAULT false,
    absolute_path VARCHAR(2048),
    platform_path VARCHAR(2048),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (subset_id) REFERENCES temp_subset(id),
    FOREIGN KEY (original_game_id) REFERENCES game(id),
    box_front VARCHAR(255),
    box_back VARCHAR(255),
    box_spine VARCHAR(255),
    box_full VARCHAR(255),
    cartridge VARCHAR(255),
    logo VARCHAR(255),
    bezel VARCHAR(255),
    panel VARCHAR(255),
    cabinet_left VARCHAR(255),
    cabinet_right VARCHAR(255),
    tile VARCHAR(255),
    banner VARCHAR(255),
    steam VARCHAR(255),
    poster VARCHAR(255),
    background VARCHAR(255),
    music VARCHAR(255),
    screenshot VARCHAR(255),
    titlescreen VARCHAR(255),
    box3d VARCHAR(255),
    steamgrid VARCHAR(255),
    fanart VARCHAR(255),
    boxtexture VARCHAR(255),
    supporttexture VARCHAR(255),
    videonormalized VARCHAR(255),
    wheelcarbon VARCHAR(255),
    wheelsteel VARCHAR(255),
    screenmarqueesmall VARCHAR(255),
    boxside VARCHAR(255),
    figurine VARCHAR(255)
);

-- 1. 创建刮削系统表
CREATE TABLE IF NOT EXISTS scraper_system (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    system_id INT UNIQUE NOT NULL,
    parent_id INT,
    name VARCHAR(255) NOT NULL,
    name_en VARCHAR(255),
    name_fr VARCHAR(255),
    name_jp VARCHAR(255),
    name_cn VARCHAR(255),
    nom_eu VARCHAR(255),
    nom_us VARCHAR(255),
    nom_launchbox VARCHAR(255),
    nom_hyperspin VARCHAR(255),
    nom_recalbox VARCHAR(255),
    nom_retropie VARCHAR(255),
    noms_commun TEXT,
    company VARCHAR(255),
    type VARCHAR(50),
    release_year INT,
    end_year INT,
    rom_type VARCHAR(50),
    support_type VARCHAR(50),
    extensions VARCHAR(200),
    icon_url VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. 为 platform 表添加刮削系统关联字段
ALTER TABLE platform ADD COLUMN IF NOT EXISTS system_id INT DEFAULT NULL;
ALTER TABLE platform ADD COLUMN IF NOT EXISTS system_region VARCHAR(10) DEFAULT NULL;
ALTER TABLE platform ADD COLUMN IF NOT EXISTS logo_region VARCHAR(10) DEFAULT NULL;
ALTER TABLE platform ADD COLUMN IF NOT EXISTS logo_type VARCHAR(50) DEFAULT NULL;

-- 3. 创建后台任务表
CREATE TABLE IF NOT EXISTS background_task (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    type VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL,
    progress INT DEFAULT 0,
    message VARCHAR(500),
    total_items BIGINT DEFAULT 0,
    processed_items BIGINT DEFAULT 0,
    start_time TIMESTAMP NULL,
    end_time TIMESTAMP NULL,
    error_message TEXT,
    description VARCHAR(500),
    result TEXT,
    `log` TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 4. 创建媒体下载任务表
CREATE TABLE IF NOT EXISTS media_download_task (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    task_id BIGINT NOT NULL,
    game_id BIGINT NOT NULL,
    game_name VARCHAR(255),
    media_type VARCHAR(50) NOT NULL,
    download_url VARCHAR(1024) NOT NULL,
    local_path VARCHAR(1024) NOT NULL,
    file_size BIGINT DEFAULT 0,
    status VARCHAR(20) DEFAULT 'PENDING',
    priority INT DEFAULT 0,
    retry_count INT DEFAULT 0,
    error_message TEXT,
    order_index BIGINT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (task_id) REFERENCES background_task(id),
    FOREIGN KEY (game_id) REFERENCES game(id)
);
