-- V1.0.17__term_mapping.sql
-- 方言映射表（TODO #10 基础设施）：多对一函数 source_term -> target_term
--   category 区分用途：system_alias（系统别名，TODO #9 平台匹配引导用）/ genre（类型归类，预留）
--   唯一键建在 (source_term, category) 上，保证 map 确定性；target 可重复
--   种子数据：常见系统别名（sfc/fc 等）→ ScreenScraper systemId，来源 system-baseline.json

CREATE TABLE IF NOT EXISTS term_mapping (
    id          BIGINT AUTO_INCREMENT PRIMARY KEY,
    source_term VARCHAR(255) NOT NULL,
    target_term VARCHAR(255) NOT NULL,
    category    VARCHAR(50)  NOT NULL DEFAULT 'system_alias',
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_term_mapping_source_category ON term_mapping(source_term, category);

-- ============ 系统别名种子数据（source_term 已归一化：小写、去空格/连字符等） ============
INSERT INTO term_mapping (source_term, target_term, category) VALUES
-- 任天堂
('sfc', '4', 'system_alias'),
('smc', '4', 'system_alias'),
('snes', '4', 'system_alias'),
('superfamicom', '4', 'system_alias'),
('supernintendo', '4', 'system_alias'),
('fc', '3', 'system_alias'),
('famicom', '3', 'system_alias'),
('nes', '3', 'system_alias'),
('nintendoentertainmentsystem', '3', 'system_alias'),
('gb', '9', 'system_alias'),
('gameboy', '9', 'system_alias'),
('gbc', '10', 'system_alias'),
('gameboycolor', '10', 'system_alias'),
('gba', '12', 'system_alias'),
('gameboyadvance', '12', 'system_alias'),
('vb', '11', 'system_alias'),
('virtualboy', '11', 'system_alias'),
('n64', '14', 'system_alias'),
('nintendo64', '14', 'system_alias'),
('gc', '13', 'system_alias'),
('ngc', '13', 'system_alias'),
('gamecube', '13', 'system_alias'),
('nintendogamecube', '13', 'system_alias'),
('nds', '15', 'system_alias'),
('nintendods', '15', 'system_alias'),
('wii', '16', 'system_alias'),
('wiiu', '18', 'system_alias'),
('3ds', '17', 'system_alias'),
('switch', '225', 'system_alias'),
('ns', '225', 'system_alias'),
('nintendoswitch', '225', 'system_alias'),
('fds', '106', 'system_alias'),
('famicomdisksystem', '106', 'system_alias'),
-- 世嘉
('md', '1', 'system_alias'),
('gen', '1', 'system_alias'),
('genesis', '1', 'system_alias'),
('megadrive', '1', 'system_alias'),
('segagenesis', '1', 'system_alias'),
('segamegadrive', '1', 'system_alias'),
('sms', '2', 'system_alias'),
('mastersystem', '2', 'system_alias'),
('gg', '21', 'system_alias'),
('gamegear', '21', 'system_alias'),
('saturn', '22', 'system_alias'),
('ss', '22', 'system_alias'),
('segasturn', '22', 'system_alias'),
('dc', '23', 'system_alias'),
('dreamcast', '23', 'system_alias'),
('segadreamcast', '23', 'system_alias'),
('32x', '19', 'system_alias'),
('sega32x', '19', 'system_alias'),
('segacd', '20', 'system_alias'),
('megacd', '20', 'system_alias'),
('sg1000', '109', 'system_alias'),
-- 索尼
('psx', '57', 'system_alias'),
('ps1', '57', 'system_alias'),
('playstation', '57', 'system_alias'),
('sonyplaystation', '57', 'system_alias'),
('ps2', '58', 'system_alias'),
('playstation2', '58', 'system_alias'),
('ps3', '59', 'system_alias'),
('playstation3', '59', 'system_alias'),
('psp', '61', 'system_alias'),
('psv', '62', 'system_alias'),
('vita', '62', 'system_alias'),
('psvita', '62', 'system_alias'),
-- 街机 / SNK
('arcade', '75', 'system_alias'),
('mame', '75', 'system_alias'),
('fba', '75', 'system_alias'),
('neogeo', '142', 'system_alias'),
('aes', '142', 'system_alias'),
('neogeocd', '70', 'system_alias'),
('ngp', '25', 'system_alias'),
('ngpc', '82', 'system_alias'),
-- NEC
('pce', '31', 'system_alias'),
('pcengine', '31', 'system_alias'),
('tg16', '31', 'system_alias'),
('turbografx', '31', 'system_alias'),
('turbografx16', '31', 'system_alias'),
('pcecd', '114', 'system_alias'),
('pcenginecd', '114', 'system_alias'),
-- 微软
('xbox', '32', 'system_alias'),
('x360', '33', 'system_alias'),
('xbox360', '33', 'system_alias'),
('msx', '113', 'system_alias'),
('msx2', '116', 'system_alias'),
-- 其他
('a2600', '26', 'system_alias'),
('atari2600', '26', 'system_alias'),
('jaguar', '27', 'system_alias'),
('atarijaguar', '27', 'system_alias'),
('lynx', '28', 'system_alias'),
('atarilynx', '28', 'system_alias'),
('wonderswan', '45', 'system_alias'),
('ws', '45', 'system_alias'),
('wsc', '46', 'system_alias'),
('wonderswancolor', '46', 'system_alias'),
('coleco', '48', 'system_alias'),
('colecovision', '48', 'system_alias');
