-- Add missing columns to game table
ALTER TABLE game ADD COLUMN IF NOT EXISTS pictoliste VARCHAR(255);
ALTER TABLE game ADD COLUMN IF NOT EXISTS pictomonochrome VARCHAR(255);
ALTER TABLE game ADD COLUMN IF NOT EXISTS pictomonochromesvg VARCHAR(255);
ALTER TABLE game ADD COLUMN IF NOT EXISTS pictocouleur VARCHAR(255);
ALTER TABLE game ADD COLUMN IF NOT EXISTS wallpaper VARCHAR(255);